### ISSUE TITLE
The integer example gives an error

### ISSUE THREAD

**Issue by dicotom** [PasaOpasen/geneticalgorithm2#1]
Set: Average time of function evaluating (secs): 9.984970092773438e-06 (total = 0.0009984970092773438)

Best score before optimization: 3.0

____________________ 1.1% GA is running...1 gen from 90...best value = 3.0Traceback (most recent call last):
  File "N:/DOWNLOADS/Roi Polanitzer GIT HUB LOTTERY FILES/LOTTERY PREDICTIONS/lotto_genetic_algorithm-main/example2.py", line 13, in <module>
    model.run(function=f)
  File "C:\Python312\Lib\site-packages\geneticalgorithm2\geneticalgorithm2.py", line 1056, in run
    ch2 = self.mut_middle(ch2, pvar1, pvar2)
  File "C:\Python312\Lib\site-packages\geneticalgorithm2\geneticalgorithm2.py", line 1186, in mut_middle
    x[i] = random.randint(v2, v1)
  File "C:\Python312\Lib\random.py", line 336, in randint
    return self.randrange(a, b+1)
  File "C:\Python312\Lib\random.py", line 301, in randrange
    istart = _index(start)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by NatanLifshitz** [comment]
This used to work, looks like something changed in python itself to cause this.

**Comment by NatanLifshitz** [comment]
Yep, this part of the library no longer works as of Python 3.12
https://docs.python.org/3/whatsnew/3.12.html#:~:text=gh%2D91760.)-,Remove,-randrange()%20functionality

**Comment by NatanLifshitz** [comment]
Thanks https://github.com/python/cpython/pull/92677
